server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/payment/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://issuer-url.com/